/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.budgetmanage.ui.consulting;

import com.budgetmanage.entities.Budget;
import com.budgetmanage.modeler.BudgetJpaController;
import com.budgetmanage.modeler.ExpendingJpaController;
import com.budgetmanage.modeler.IngressJpaController;
import com.budgetmanage.modeler.exceptions.NonexistentEntityException;
import com.budgetmanage.ui.Main;
import com.budgetmanage.ui.maintenance.FinancesAddFrm;
import com.budgetmanage.util.Constant;
import com.budgetmanage.util.LineChart;
import com.budgetmanage.util.PieChart;
import com.budgetmanage.util.PieSlice;
import java.awt.BorderLayout;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nestor_Velasquez
 */
public class MainPanel extends javax.swing.JPanel implements Constant{

    /**
     * Creates new form MainPanel
     */
    EntityManagerFactory emf;
    BudgetJpaController bjc;
    ExpendingJpaController ejc;
    IngressJpaController ijc;
    JPanel panel;
    
    public MainPanel(JPanel panel) {
        initComponents();        
        jLabel13.setText(MAIN_PANEL_TITLE);
        String name = Main.getUser().getNombre().trim();
        String lastName = Main.getUser().getApellidos().trim();
        
        //If the user contains two names, we show the first one
        if(name.contains(" ")){
            name = name.substring(0, name.indexOf(" "));
        }
        //If the user contains two lastnames, we show the first one
        if(lastName.contains(" ")){
            lastName = lastName.substring(0, lastName.indexOf(" "));
        }
        
        jLabel4.setText("Bienvenid@ "+name +" "+lastName);
       
        emf = Persistence.createEntityManagerFactory(PU);
        
        bjc = new BudgetJpaController(emf);
        ijc = new IngressJpaController(emf);
        ejc = new ExpendingJpaController(emf);
        
        loadWindow();
        this.panel = panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BudgeManagePUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("BudgeManagePU").createEntityManager();
        budgetQuery = java.beans.Beans.isDesignTime() ? null : BudgeManagePUEntityManager.createQuery("SELECT b FROM Budget b");
        budgetList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : budgetQuery.getResultList();
        budgetQuery1 = java.beans.Beans.isDesignTime() ? null : BudgeManagePUEntityManager.createQuery("SELECT b FROM Budget b");
        budgetList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : budgetQuery1.getResultList();
        accountQuery = java.beans.Beans.isDesignTime() ? null : BudgeManagePUEntityManager.createQuery("SELECT a FROM Account a");
        accountList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : accountQuery.getResultList();
        budgetQuery2 = java.beans.Beans.isDesignTime() ? null : BudgeManagePUEntityManager.createQuery("SELECT b FROM Budget b");
        budgetList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : budgetQuery2.getResultList();
        resumeBuPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumeTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        generatePanel = new javax.swing.JPanel();
        nameTextField = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        flowPanel = new javax.swing.JPanel();
        resumeExPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        financesPanel = new javax.swing.JPanel();
        ckbIngress = new javax.swing.JCheckBox();
        ckbExpendings = new javax.swing.JCheckBox();
        btnGenerarI = new javax.swing.JButton();
        btnGenerarG = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(Constant.BKG);

        resumeBuPanel.setBackground(Constant.BKG);
        resumeBuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen del Presupuesto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10), new java.awt.Color(0, 0, 0))); // NOI18N

        resumeTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 255)));
        resumeTable.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        resumeTable.setGridColor(new java.awt.Color(204, 255, 204));
        jScrollPane1.setViewportView(resumeTable);

        javax.swing.GroupLayout resumeBuPanelLayout = new javax.swing.GroupLayout(resumeBuPanel);
        resumeBuPanel.setLayout(resumeBuPanelLayout);
        resumeBuPanelLayout.setHorizontalGroup(
            resumeBuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        resumeBuPanelLayout.setVerticalGroup(
            resumeBuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resumeBuPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Consultar Finanzas");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        generatePanel.setBackground(Constant.BKG);
        generatePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Generar Presupuesto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, TITLE_FONT, new java.awt.Color(0, 0, 0)));
        generatePanel.setToolTipText("Generar presupuesto");

        nameTextField.setToolTipText("Nombre Del Presupuesto");

        generateButton.setMnemonic(KeyEvent.VK_ENTER);
        generateButton.setText("Generar");
        generateButton.setToolTipText("Generar presupuesto");
        generateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateButtonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre del presupuesto");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Semanal", "Quincenal", "Mensual" }));
        jComboBox1.setToolTipText("Tiempo de vida del presupuesto");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tiempo Presupuestario");

        javax.swing.GroupLayout generatePanelLayout = new javax.swing.GroupLayout(generatePanel);
        generatePanel.setLayout(generatePanelLayout);
        generatePanelLayout.setHorizontalGroup(
            generatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(generatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox1, 0, 107, Short.MAX_VALUE)
                        .addComponent(nameTextField))
                    .addComponent(generateButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        generatePanelLayout.setVerticalGroup(
            generatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generatePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(generatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField))
                .addGap(3, 3, 3)
                .addGroup(generatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        flowPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flujo Del Gasto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10), java.awt.Color.black)); // NOI18N
        flowPanel.setLayout(new java.awt.BorderLayout());

        resumeExPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen de Gastos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10))); // NOI18N
        resumeExPanel.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Presupuesto Sobregirado!");
        jLabel3.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("No tiene Presupuestos generados");

        financesPanel.setBackground(BKG);
        financesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Finanzas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, TITLE_FONT));
        financesPanel.setToolTipText("Debe generar ingresos o gastos para iniciar");

        ckbIngress.setBackground(BKG);
        ckbIngress.setText("Ingresos registrados");
        ckbIngress.setEnabled(false);
        ckbIngress.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbIngressItemStateChanged(evt);
            }
        });

        ckbExpendings.setBackground(BKG);
        ckbExpendings.setText("Gastos registrados");
        ckbExpendings.setEnabled(false);
        ckbExpendings.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbExpendingsItemStateChanged(evt);
            }
        });

        btnGenerarI.setText("Registrar Ingresos");
        btnGenerarI.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGenerarI.setPreferredSize(new java.awt.Dimension(119, 18));
        btnGenerarI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarIMouseClicked(evt);
            }
        });

        btnGenerarG.setText("Registrar Gastos");
        btnGenerarG.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGenerarG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarGMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Generar los conceptos indicados para iniciar");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout financesPanelLayout = new javax.swing.GroupLayout(financesPanel);
        financesPanel.setLayout(financesPanelLayout);
        financesPanelLayout.setHorizontalGroup(
            financesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(financesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(financesPanelLayout.createSequentialGroup()
                        .addComponent(ckbExpendings)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerarG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(financesPanelLayout.createSequentialGroup()
                        .addGroup(financesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(financesPanelLayout.createSequentialGroup()
                                .addComponent(ckbIngress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGenerarI, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        financesPanelLayout.setVerticalGroup(
            financesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, financesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(financesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ckbExpendings)
                    .addComponent(btnGenerarG, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(financesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbIngress)
                    .addComponent(btnGenerarI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resumeExPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 968, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(resumeBuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(flowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(generatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(financesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resumeBuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(flowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resumeExPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(279, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(financesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        resumeBuPanel.setVisible(false);
        generatePanel.setVisible(false);
        flowPanel.setVisible(false);
        flowPanel.setBackground(Constant.BKG);
        resumeExPanel.setVisible(false);
        resumeExPanel.setBackground(Constant.BKG);
        jLabel3.setVisible(false);
        jLabel1.setVisible(false);
        financesPanel.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateButtonMouseClicked
        String name = nameTextField.getText().trim();
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "Coloque un nombre para el presupuesto", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }else if(jComboBox1.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Seleccione un tiempo de presupuesto", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            //Generate the budgets
            generateBudget(name);
        }
    }//GEN-LAST:event_generateButtonMouseClicked

    private void ckbIngressItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbIngressItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            btnGenerarI.setEnabled(false);
        }else{
            btnGenerarI.setEnabled(false);
        }
    }//GEN-LAST:event_ckbIngressItemStateChanged

    private void ckbExpendingsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbExpendingsItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            btnGenerarG.setEnabled(false);
        }else{
            btnGenerarG.setEnabled(false);
        }
    }//GEN-LAST:event_ckbExpendingsItemStateChanged

    private void btnGenerarIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarIMouseClicked
        FinancesAddFrm faf = new FinancesAddFrm(2);
        com.budgetmanage.util.Util.addPanel(panel, faf);
    }//GEN-LAST:event_btnGenerarIMouseClicked

    private void btnGenerarGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarGMouseClicked
        FinancesAddFrm faf = new FinancesAddFrm(1);
        com.budgetmanage.util.Util.addPanel(panel, faf);
    }//GEN-LAST:event_btnGenerarGMouseClicked
    
    /*
     * @method this method generate the first budget in case of no one exists.
     */
    private void generateBudget(String name){
        //Defining attiributes for the budgets.
            boolean isOk = true;
            double expendigTotal = 0;
            double ingressTotal = 0;
            int days = 0;
            Date actualDate = new Date();
            Timestamp date = new Timestamp(actualDate.getTime());
            
            switch(jComboBox1.getSelectedIndex()){
                case 1:{
                    days = 7;
                    break;
                }
                case 2:{
                    days = 15;
                    break;
                }
                case 3:{
                    days = 30;
                    break;
                }                
            }
            expendigTotal = ejc.getExpendingTotal();
            ingressTotal = ijc.getIngressTotal();
            
            if(expendigTotal == 0){
                JOptionPane.showMessageDialog(this, "No tiene gastos registrados", "Error", JOptionPane.ERROR_MESSAGE);
                isOk = false;
            }
            
            if(ingressTotal == 0){
                JOptionPane.showMessageDialog(this, "No tiene ingresos registrados", "Error", JOptionPane.ERROR_MESSAGE);
                isOk = false;
            }            
            
            if(isOk){

                //Creating and persisting the budgets.                
                Budget budget = new Budget(name, "A", expendigTotal, ingressTotal, date, date, Main.getUser(), days);                
                bjc.create(budget);
                jLabel1.setText("El Presupuesto se genero correctamente");
            }
            nameTextField.setText("");            
            //Reloading the window after generate the budget.
            loadWindow();
    }
    
    /*
     * @method load the corresponding panels according to the state of then user (with finances or without finances)
     */
    private void loadWindow(){
        Budget budget;
        double expendings = ejc.getExpendingTotal();
        double ingresses = ijc.getIngressTotal();
        boolean generate = true;
        
        //If the user has not expending yet, we ask him for register them, else we mark it as yes.
        if(expendings == 0){            
            ckbExpendings.setSelected(false);
            generate = false;
        }else{
            ckbExpendings.setSelected(true);                    
        }
        
        //If the user has not register yet, we ask him for register them, else we mark it as yes.
        if(ingresses == 0){            
            ckbIngress.setSelected(false);
            generate = false;
        }else{
            ckbIngress.setSelected(true);
        }

        if(generate){
            try {
                //If everything is ok we prepare the main window.
                
                //Get the actual budget.
                budget = bjc.getActual(Main.getUser().getId());
                
                //Formating the dates of the budget.
                String generatedDate = new SimpleDateFormat(Constant.FORMAT_DATE).format(budget.getGenerateDate());
                String updatedDate = new SimpleDateFormat(Constant.FORMAT_DATE).format(budget.getUpdateDate());
                //Creating a table model
                DefaultTableModel model  = new DefaultTableModel(BUDGET_TABLE_COLS, 1);
                
                resumeTable.setModel(model);
                model.insertRow(0, new Object[]{budget.getId(),budget.getName(),
                    budget.getIngressTotal(), budget.getExpendingTotal(), (budget.getIngressTotal() - budget.getExpendingTotal()), generatedDate, updatedDate});
                resumeTable.updateUI();

                if(budget.getExpendingTotal() > budget.getIngressTotal()){
                    jLabel3.setVisible(true);
                }
                resumeBuPanel.setVisible(true);
                flowPanel.setVisible(true);
                resumeExPanel.setVisible(true);
                generatePanel.setVisible(false); 

                fillExpendingChart();
                this.updateUI();
            } catch (NonexistentEntityException ex) {
                    jLabel1.setVisible(true);
                    jLabel1.setText("No tiene Presupuestos generados");
                    generatePanel.setVisible(true);
            }
        }else{
            financesPanel.setVisible(true);
            jLabel1.setText("Debe registrar sus finanzas para iniciar");
        }
        
    }
    
    /*
     * @method fillExpendingChart: fills the line and pie charts of expendings for this budget.
     */
    private void fillExpendingChart(){
        List<PieSlice> slices = new ArrayList<>();
        
        //Look for the totals expendings according to its category.
        double fixedExpendingTotal = ejc.getExpendigsTotal(1);
        double servicesExpendingTotal = ejc.getExpendigsTotal(2);
        double leisureExpendingTotal = ejc.getExpendigsTotal(3);
        
        //Adding slices for the pie.
        slices.add(new PieSlice(FIXED_EXPENSE_COLOR, fixedExpendingTotal, "Total de gastos fijos"));
        slices.add(new PieSlice(SERVICES_COLOR, servicesExpendingTotal, "Total de gastos por servicios"));
        slices.add(new PieSlice(LEISURE_COLOR, leisureExpendingTotal, "Total de gastos por ocio y demas"));
        
        //Creating a pie chart and adding to its corresponding panel.
        PieChart pieChart = new PieChart(slices);
        resumeExPanel.add(pieChart, BorderLayout.CENTER);
        
        List<Object[]> objs = ejc.getExpendingTotalByDay();
        double[] exps = new double[objs.size()+1];

        //look for porcentage of the values to make the line chart with them.
        for(int i =0; i < objs.size(); i++){
            Object[] obj = objs.get(i);
            if(i==0){
                exps[i] = (double)obj[0];
                exps[i+1] = (double)obj[0];
            }else{
                exps[i+1] = exps[i-1]+(double)obj[0];
            }
        }
        
        //Add a line chart depending the expense of the budget.
        flowPanel.add(new LineChart(exps), BorderLayout.CENTER);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager BudgeManagePUEntityManager;
    private java.util.List<com.budgetmanage.entities.Account> accountList;
    private javax.persistence.Query accountQuery;
    private javax.swing.JButton btnGenerarG;
    private javax.swing.JButton btnGenerarI;
    private java.util.List<com.budgetmanage.entities.Budget> budgetList;
    private java.util.List<com.budgetmanage.entities.Budget> budgetList1;
    private java.util.List<com.budgetmanage.entities.Budget> budgetList2;
    private javax.persistence.Query budgetQuery;
    private javax.persistence.Query budgetQuery1;
    private javax.persistence.Query budgetQuery2;
    private javax.swing.JCheckBox ckbExpendings;
    private javax.swing.JCheckBox ckbIngress;
    private javax.swing.JPanel financesPanel;
    private javax.swing.JPanel flowPanel;
    private javax.swing.JButton generateButton;
    private javax.swing.JPanel generatePanel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel resumeBuPanel;
    private javax.swing.JPanel resumeExPanel;
    private javax.swing.JTable resumeTable;
    // End of variables declaration//GEN-END:variables
}
