/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.budgetmanage.ui;

/**
 *
 * @author Fulvio
 */
public class Consulting extends javax.swing.JPanel {

    /**
     * Creates new form Consulting
     */
    public Consulting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setOpaque(false);
        setLayout(null);
        add(jTextField1);
        jTextField1.setBounds(32, 48, 44, 20);

        jLabel1.setText("Finanza");
        add(jLabel1);
        jLabel1.setBounds(82, 51, 37, 14);

        jLabel2.setText("Consultando prueba 1");
        add(jLabel2);
        jLabel2.setBounds(137, 11, 106, 14);

        jButton1.setText("ok");
        add(jButton1);
        jButton1.setBounds(82, 79, 43, 23);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
