/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.budgetmanage.ui.Maintenance;

import java.awt.event.ItemEvent;

/**
 *
 * @author Nestor_Velasquez
 */
public class FinancesMaintenanceFrm extends javax.swing.JPanel {

    /**
     * Creates new form FinancesMaintenanceFrm
     */
    public FinancesMaintenanceFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel1.setText("Finanzas");
        add(jLabel1);
        jLabel1.setBounds(230, 10, 73, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Ingreso", "Gasto", "Presupuesto" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(30, 60, 110, 20);
        add(jTextField1);
        jTextField1.setBounds(30, 90, 85, 20);
        jTextField1.setVisible(false);

        jButton1.setText("Buscar");
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(310, 90, 70, 23);
        jButton1.setVisible(false);

        jCheckBox1.setText("Buscar todos");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        add(jCheckBox1);
        jCheckBox1.setBounds(30, 130, 120, 23);
        jCheckBox1.setVisible(false);

        jButton2.setText("Nuevo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(310, 130, 65, 23);
        jButton2.setVisible(false);

        jLabel2.setText("Nombre del "+jComboBox1.getSelectedItem().toString());
        add(jLabel2);
        jLabel2.setBounds(120, 90, 145, 23);
        jLabel2.setVisible(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Monto", "Fecha Modificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.setVisible(false);
        //jTable1.setVisible(false);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 190, 446, 94);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*Seleccione un tipo de finanza");
        add(jLabel3);
        jLabel3.setBounds(160, 60, 145, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("seleccione")){
            jScrollPane1.setVisible(false);
            jButton1.setVisible(false);
            jTextField1.setVisible(false);
            jLabel2.setVisible(false);
            jCheckBox1.setVisible(false);
            jButton2.setVisible(false);
            jLabel3.setVisible(true);
        }
        else{
            //jScrollPane1.setVisible(true);
            jCheckBox1.setVisible(true);
            jButton1.setVisible(true);
            jTextField1.setVisible(true);
            jLabel2.setVisible(true);
            jButton2.setVisible(true);
            jLabel3.setVisible(false);
            jLabel2.setText("Nombre del "+jComboBox1.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jCheckBox1.setVisible(false);
        jScrollPane1.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //jCheckBox1.setVisible(false);
        //jScrollPane1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            jButton1.setVisible(false);
            jTextField1.setVisible(false);
            jLabel2.setVisible(false);
            jScrollPane1.setVisible(true);

        }else{
            jButton1.setVisible(true);
            jTextField1.setVisible(true);
            jLabel2.setVisible(true);
            jScrollPane1.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
    }//GEN-LAST:event_jButton2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
